--- 
apiVersion: v1
kind: Namespace
metadata: 
  name: glusterstorage

---
apiVersion: v1
data: 
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJtdHIuZXh0ZXJuYWwub3RjLnRlbGVrb21jbG91ZC5jb20iOiB7CiAgICAgICJhdXRoIjogImJXTnpjSE1yYlhSeVpHVndiRzk1WlhJNlZsZzJSVFJLVXpJeVRFUktUVkJVTWpreU0xQlFPVTFVV2sweE0wNVVOVVJST1RNeU1ETkpWbFJNU2sxQlVVdEhXVmsxVlRJeldWWkhWVVkyU1VwWk1nPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
kind: Secret
metadata: 
  name: mcsps-mtrdeployer-pull-secret
  namespace: glusterstorage
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: glusterdeploy
  namespace: glusterstorage

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: glusterdeploy-role
rules: 
  - 
    apiGroups: 
      - ""
      - extensions
      - apps
      - autoscaling
      - batch
      - networking.k8s.io
      - policy
      - authentication.k8s.io
      - storage.k8s.io
      - certmanager.k8s.io
      - rbac.authorization.k8s.io
    resources: 
      - "*"
    verbs: 
      - "*"

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: glusterdeploy-rolebinding
roleRef: 
  apiGroup: ""
  kind: ClusterRole
  name: glusterdeploy-role
subjects: 
  - 
    kind: ServiceAccount
    name: glusterdeploy
    namespace: glusterstorage

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: glusterdeploy
  name: gluster-deployment
  namespace: glusterstorage
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: glusterdeploy
  template: 
    metadata: 
      labels: 
        app: glusterdeploy
    spec: 
      containers: 
        - 
          command: 
            - /docker-entrypoint.sh
          image: "mtr.external.otc.telekomcloud.com/mcsps/glusterdeploy:master"
          imagePullPolicy: Always
          name: glusterdeploy
      imagePullSecrets: 
        - 
          name: mcsps-mtrdeployer-pull-secret
      serviceAccountName: glusterdeploy
