kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sata
provisioner: kubernetes.io/cinder
parameters:
  type: SATA

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sas
provisioner: kubernetes.io/cinder
parameters:
  type: SAS

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
provisioner: kubernetes.io/cinder
parameters:
  type: SSD