--- 
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-staging
  namespace: cert-manager
spec: 
  acme: 
    email: mcs-dis@telekom.de
    http01: {}
    privateKeySecretRef: 
      name: letsencrypt-staging
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"

--- 
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-production
  namespace: cert-manager
spec: 
  acme: 
    email: mcs-dis@telekom.de
    http01: {}
    privateKeySecretRef: 
      name: letsencrypt-production
    server: "https://acme-v02.api.letsencrypt.org/directory"
