---
apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJtdHIuZXh0ZXJuYWwub3RjLnRlbGVrb21jbG91ZC5jb20iOiB7CiAgICAgICJhdXRoIjogImJXTnpjSE1yYlhSeVpHVndiRzk1WlhJNlZsZzJSVFJLVXpJeVRFUktUVkJVTWpreU0xQlFPVTFVV2sweE0wNVVOVVJST1RNeU1ETkpWbFJNU2sxQlVVdEhXVmsxVlRJeldWWkhWVVkyU1VwWk1nPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
kind: Secret
metadata:
  name: mcsps-mtrdeployer-pull-secret
  namespace: ingress-nginx
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: ingress-nginx
rules:
  -
    apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - watch
      - list
  -
    apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  -
    apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list
  -
    apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  -
    kind: ServiceAccount
    name: external-dns
    namespace: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: external-dns
  name: external-dns-deployment
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        -
          args:
            - "--domain-filter=mcsps.telekomcloud.com"
            - "--source=ingress"
            - "--source=service"
            - "--provider=designate"
            - "--registry=txt"
            - "--txt-prefix=_mcs_"
            - "--txt-owner-id=$(K8S_NAME)"
            - "--log-level=debug"
            - "--interval=10s"
            - "--policy=upsert-only"
          env:
            -
              name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  key: OS_AUTH_URL
                  name: otcdnscred
            -
              name: OS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_REGION_NAME
                  name: otcdnscred
            -
              name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  key: OS_USERNAME
                  name: otcdnscred
            -
              name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: OS_PASSWORD
                  name: otcdnscred
            -
              name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_PROJECT_NAME
                  name: otcdnscred
            -
              name: OS_USER_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  key: OS_USER_DOMAIN_NAME
                  name: otcdnscred
            -
              name: K8S_NAME
              valueFrom:
                secretKeyRef:
                  key: K8S_NAME
                  name: otcdnscred
          image: "registry.opensource.zalan.do/teapot/external-dns:v0.5.16"
          name: external-dns
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
      serviceAccountName: external-dns
