---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata: 
  name: external-dns
  namespace: ingress-nginx
rules: 
  - 
    apiGroups: 
      - ""
    resources: 
      - services
    verbs: 
      - get
      - watch
      - list
  - 
    apiGroups: 
      - ""
    resources: 
      - pods
    verbs: 
      - get
      - watch
      - list
  - 
    apiGroups: 
      - extensions
    resources: 
      - ingresses
    verbs: 
      - get
      - watch
      - list
  - 
    apiGroups: 
      - ""
    resources: 
      - nodes
    verbs: 
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata: 
  name: external-dns-viewer
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects: 
  - 
    kind: ServiceAccount
    name: external-dns
    namespace: ingress-nginx
--- 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: externaldns
    kubebuilder.k8s.io: 1.0.0
  name: dnsendpoints.externaldns.k8s.io
spec:
  group: externaldns.k8s.io
  names:
    kind: DNSEndpoint
    plural: dnsendpoints
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            endpoints:
              items:
                properties:
                  dnsName:
                    type: string
                  labels:
                    type: object
                  providerSpecific:
                    items:
                      properties:
                        name: 
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  recordTTL:
                    format: int64
                    type: integer
                  recordType:
                    type: string
                  targets:
                    items:
                      type: string
                    type: array
                type: object
              type: array
          type: object
        status:
          properties:
            observedGeneration:
              format: int64
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: external-dns
  namespace: ingress-nginx
spec: 
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: external-dns
    spec: 
      containers: 
        - 
          args: 
            - "--log-level=debug"
            - "--source=service"
            - "--source=ingress"
            - "--domain-filter=mcskube.de"
            - "--provider=designate"
            - "--registry=txt"
            - "--txt-prefix=_mcs_"
            - "--txt-owner-id=mcs"
            - "--policy=upsert-only"
          env: 
            - 
              name: OS_AUTH_URL
              valueFrom: 
                secretKeyRef: 
                  key: OS_AUTH_URL
                  name: otccred
            - 
              name: OS_REGION_NAME
              valueFrom: 
                secretKeyRef: 
                  key: OS_REGION_NAME
                  name: otccred
            - 
              name: OS_USERNAME
              valueFrom: 
                secretKeyRef: 
                  key: OS_USERNAME
                  name: otccred
            - 
              name: OS_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: OS_PASSWORD
                  name: otccred
            - 
              name: OS_PROJECT_NAME
              valueFrom: 
                secretKeyRef: 
                  key: OS_PROJECT_NAME
                  name: otccred
            - 
              name: OS_USER_DOMAIN_NAME
              valueFrom: 
                secretKeyRef: 
                  key: OS_USER_DOMAIN_NAME
                  name: otccred
          image: "registry.opensource.zalan.do/teapot/external-dns:latest"
          name: external-dns
          resources: 
            requests: 
              cpu: 50m
              memory: 50Mi
      serviceAccountName: external-dns
---