apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: ingress-nginx
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: ingress-nginx
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: ingress-nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: ingress-nginx
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image:  registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --log-level=debug
        - --source=service
        - --source=ingress
        - --domain-filter=mcskube.de
        - --provider=designate
        - --registry=txt
        - --txt-prefix=_mcs_
        - --txt-owner-id=mcs
        - --policy=upsert-only
        env: # values from openrc file
        - name: OS_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: otccred
              key: OS_AUTH_URL
        - name: OS_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: otccred
              key: OS_REGION_NAME
        - name: OS_USERNAME
          valueFrom:
            secretKeyRef:
              name: otccred
              key: OS_USERNAME
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: otccred
              key: OS_PASSWORD
        - name: OS_PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: otccred
              key: OS_PROJECT_NAME
        - name: OS_USER_DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: otccred
              key: OS_USER_DOMAIN_NAME
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
            